                    <li class="last">
                        <div class="box-email"><span class="pull-left"><em class="fa fa-envelope-o">&nbsp;</em></span>
                            <div class="media-body pull-left">
                                <p>
                                <a href="mailto:<?php echo !empty($block->getEmail()['header_email']) ?$block->getEmail()['header_email']:'';?>">
                                    <?php echo !empty($block->getEmail()['header_email']) ?$block->getEmail()['header_email']:'';?>
                               </p>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div class="header-top-right col-lg-4 col-md-4 col-sm-8 col-xs-12 ">
					    
					    <div class="dropdown currency_top">
							
    
    <div class="switcher currency-switcher">
        <div class="dropdown-toggle cover">
            <div>
                <div class="label">Currency:</div>
                <div class="value">USD</div>
                <div class="caret">&nbsp;</div>
            </div>
        </div>
        <ul class="dropdown-switcher"><li><a href="http://m1.alothemes.com/smile/index.php/directory/currency/switch/currency/EUR/uenc/aHR0cDovL20xLmFsb3RoZW1lcy5jb20vc21pbGUvP19fX3N0b3JlPWVuZ2xpc2g,/">EUR</a></li><li class="current">USD</li></ul>    </div>
						</div>
						<div class="dropdown top-form-language">
								
    <div class="switcher lang-switcher">
        <div class="dropdown-toggle">
            <div>
            	<div class="label dropdown-icon flag" style="background-image:url(http://m1.alothemes.com/smile/skin/frontend/alosmile/default/images/flags/english.png)">&nbsp;</div>
                <div class="value">English</div>
                <div class="caret">&nbsp;</div>
            </div>
        </div>
            <ul class="dropdown-switcher">
                <li class="current"><span class="label dropdown-icon" style="background-image:url(http://m1.alothemes.com/smile/skin/frontend/alosmile/default/images/flags/english.png);">&nbsp;</span>English</li><li><a href="http://m1.alothemes.com/smile/index.php/?___store=french&amp;___from_store=english"><span class="label dropdown-icon" style="background-image:url(http://m1.alothemes.com/smile/skin/frontend/alosmile/default/images/flags/french.png);">&nbsp;</span>French</a></li><li><a href="http://m1.alothemes.com/smile/index.php/?___store=german&amp;___from_store=english"><span class="label dropdown-icon" style="background-image:url(http://m1.alothemes.com/smile/skin/frontend/alosmile/default/images/flags/german.png);">&nbsp;</span>German</a></li>
            </ul>
            </div>
	</div>
	<div class="dropdown toplinks">
	    <div class="switcher links-switcher">
            <a href="#" class="login_click">Account</a>
            <div class="dropdown-switcher">
                <ul class="links">
                    <li class="first"><a href="http://m1.alothemes.com/smile/index.php/wishlist/" title="My Wishlist">My Wishlist</a></li>
                    <li><a href="http://m1.alothemes.com/smile/index.php/checkout/" title="Checkout" class="top-link-checkout">Checkout</a></li>
                    <li><a href="http://m1.alothemes.com/smile/index.php/testimonial/" title="Testimonial">Testimonial</a></li>
                    <li class=" last"><a href="http://m1.alothemes.com/smile/index.php/customer/account/login/" title="Log In">Log In</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>            



    </div>
</div>