<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="footer-container">
    <div class="footer">
        <?= $block->getChildHtml() ?>
        <p class="bugs"><?= /* @escapeNotVerified */ __('Help Us Keep Magento Healthy') ?> - <a
            href="http://www.magentocommerce.com/bug-tracking"
            target="_blank"><strong><?= /* @escapeNotVerified */ __('Report All Bugs') ?></strong></a>
        </p>
        <address><?= /* @escapeNotVerified */ $block->getCopyright() ?></address>
    </div>
</div>

<div class="alo footer-container">
    <div class="block-footer-top">
        <div class="container">
            <div class="row show-grid">
                <div class="footer">
                         <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
<div class="block-static2 static-alo">
<div class="block block-about">
<div class="block-title"><strong> <span>About Store</span> </strong></div>
</div>
<span class="toggle-tab mobile" style="display: none;"><span class="hidden">hidden</span></span>
<div class="toggle-content">
<div class="logo-footer"><img class="icon-about" alt="Smile" src="http://m1.alothemes.com/smile/media/wysiwyg/alothemes/static/logo-footer.png">
<p>Sed ut perspiciatis unde omnis iste natus voluptatem accusantium doloremque lauda totam rem aperiam sunshine love.</p>
</div>
<div class="social-links icon-wrapper"><a class="icon-facebook" href="#"><em class="fa fa-facebook">&nbsp;</em></a> <a class="icon-twitter" href="#"><em class="fa fa-twitter">&nbsp;</em></a> <a class="icon-rss" href="#"><em class="fa fa-rss">&nbsp;</em></a> <a class="icon-envelope " href="#"><em class="fa fa-envelope ">&nbsp;</em></a> <a class="icon-pinterest" href="#"><em class="fa fa-pinterest">&nbsp;</em></a> <a class="icon-instagram" href="#"><em class="fa fa-instagram">&nbsp;</em></a></div>
</div>
</div>
</div>
<div class="customer col-lg-3 col-md-3 col-sm-3 col-xs-12">
<div class="block-static3 static-alo">
<div class="block block-creare-twitter">
	<div class="block-title"><strong><span>Our Latest Tweets</span></strong></div>
	<span class="toggle-tab mobile" style="display: none;"><span class="hidden">hidden</span></span>
    <div class="block-content toggle-content">
    	<ul>
		        	<li>
                <p class="twitter-pic">
                    <a href="https://twitter.com/alothemes"><img src="http://pbs.twimg.com/profile_images/536002680057913345/j7c9SpAr_normal.png" alt="twitter icon"></a>
                </p>
				<p class="twitter-links">
					<span class="tweetprofilelink">
						<strong><a href="https://twitter.com/alothemes">alothemes</a></strong>
						<a href="https://twitter.com/alothemes">@alothemes</a>
					</span>
					Install only template wordpress ALO Themes: <a target="_Blank" href="https://t.co/XHjkgJIn63">https://t.co/XHjkgJIn63</a> via @YouTube					<span> - 426 days ago</span>
				</p>
            </li>
                	<li>
                <p class="twitter-pic">
                    <a href="https://twitter.com/alothemes"><img src="http://pbs.twimg.com/profile_images/536002680057913345/j7c9SpAr_normal.png" alt="twitter icon"></a>
                </p>
				<p class="twitter-links">
					<span class="tweetprofilelink">
						<strong><a href="https://twitter.com/alothemes">alothemes</a></strong>
						<a href="https://twitter.com/alothemes">@alothemes</a>
					</span>
					Install quickstart wordpress ALO Themes.: <a target="_Blank" href="https://t.co/mg5XEDrDZg">https://t.co/mg5XEDrDZg</a> via @YouTube					<span> - 426 days ago</span>
				</p>
            </li>
                        </ul>
    </div>
</div>



</div>
</div>
<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12"><div class="block block-tags">
    <div class="block-title">
        <strong><span>Popular Tags</span></strong>
    </div>
	<span style="display: none;" class="toggle-tab mobile"><span class="hidden">hidden</span></span>
    <div class="block-content toggle-content">
        <ul class="tags-list">
                            <li><a href="http://m1.alothemes.com/smile/index.php/tag/product/list/tagId/13/" style="font-size:95%;">beauty</a></li>
                            <li><a href="http://m1.alothemes.com/smile/index.php/tag/product/list/tagId/9/" style="font-size:95%;">collection</a></li>
                            <li><a href="http://m1.alothemes.com/smile/index.php/tag/product/list/tagId/10/" style="font-size:95%;">design</a></li>
                            <li><a href="http://m1.alothemes.com/smile/index.php/tag/product/list/tagId/11/" style="font-size:95%;">forever</a></li>
                            <li><a href="http://m1.alothemes.com/smile/index.php/tag/product/list/tagId/8/" style="font-size:95%;">gallery</a></li>
                            <li><a href="http://m1.alothemes.com/smile/index.php/tag/product/list/tagId/14/" style="font-size:95%;">magento</a></li>
                            <li><a href="http://m1.alothemes.com/smile/index.php/tag/product/list/tagId/6/" style="font-size:95%;">news</a></li>
                            <li><a href="http://m1.alothemes.com/smile/index.php/tag/product/list/tagId/12/" style="font-size:95%;">photos</a></li>
                            <li><a href="http://m1.alothemes.com/smile/index.php/tag/product/list/tagId/3/" style="font-size:95%;">products</a></li>
                            <li><a href="http://m1.alothemes.com/smile/index.php/tag/product/list/tagId/7/" style="font-size:95%;">smile</a></li>
                            <li><a href="http://m1.alothemes.com/smile/index.php/tag/product/list/tagId/5/" style="font-size:95%;">sports</a></li>
                    </ul>
        <div class="actions">
            <a href="http://m1.alothemes.com/smile/index.php/tag/list/">View All Tags</a>
        </div>
    </div>
</div>
</div>
<div class="customer col-lg-3 col-md-3 col-sm-3 col-xs-12">
<div class="block-static4 static-alo"><div class="block block-subscribe">
    <div class="block-title">
        <strong><span>Newsletter</span></strong>
    </div>
	<span style="display: none;" class="toggle-tab mobile"><span class="hidden">hidden</span></span>
    <form action="http://m1.alothemes.com/smile/index.php/newsletter/subscriber/new/" method="post" id="newsletter-validate-detail">
        <div class="block-content toggle-content">
            <div class="form-subscribe-header">
                <label for="newsletter">Sign Up for Our Newsletter:</label>
            </div>
            <div class="input-box">
               <input type="text" name="email" id="newsletter" title="Sign up for our newsletter" class="input-text required-entry validate-email">
            </div>
            <div class="actions">
                <button type="submit" title="Subscribe" class="button"><span><span>Subscribe</span></span></button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
    </script>
</div>
</div>
</div>                 </div>
            </div>
        </div>
    </div>
    <div class="block-footer-copyright">
        <div class="container">
            <div class="footer">
				<div class="row">
					<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 pull-left">
						<ul class="links">
<li class="first"><a href="http://m1.alothemes.com/smile/index.php/catalog/seo_sitemap/category/">Site Map</a></li>
<li><a href="http://m1.alothemes.com/smile/index.php/catalogsearch/term/popular/">Search Terms</a></li>
<li><a href="http://m1.alothemes.com/smile/index.php/catalogsearch/advanced">Advanced Search</a></li>
<li><a href="http://m1.alothemes.com/smile/index.php/sales/guest/form">Orders and Returns</a></li>
<li class="last"><a href="http://m1.alothemes.com/smile/index.php/contacts">Contact Us</a></li>
</ul>												 <address>Copyright 2015 · <a href="#">Designed by Smile Nguyen</a>. All rights reserved</address>
					 </div>
					 <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 pull-right">
							 <div class="paypal hidden-xs">
								 <p><img class="img-responsive" src="http://m1.alothemes.com/smile/media/wysiwyg/alothemes/static/paypal.png" alt=""></p>								 							 </div>
					 </div>
				</div>	 
            </div>
        </div>
    </div>
	<a href="#" id="backtotop" style="display: block;"><span class="fa fa-angle-up"></span><span class="back-to-top">Back to Top</span></a>
</div>