<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
    <div class="block block-tags">
        <div class="block-title">
            <strong><span>Popular Tags</span></strong>
        </div>
        <span style="display: none;" class="toggle-tab mobile"><span class="hidden">hidden</span></span>
        <div class="block-content toggle-content">
            <ul class="tags-list">
                <li><a href="http://m1.alothemes.com/smile/index.php/tag/product/list/tagId/13/" style="font-size:95%;">beauty</a></li>
                <li><a href="http://m1.alothemes.com/smile/index.php/tag/product/list/tagId/9/" style="font-size:95%;">collection</a></li>
                <li><a href="http://m1.alothemes.com/smile/index.php/tag/product/list/tagId/10/" style="font-size:95%;">design</a></li>
                <li><a href="http://m1.alothemes.com/smile/index.php/tag/product/list/tagId/11/" style="font-size:95%;">forever</a></li>
                <li><a href="http://m1.alothemes.com/smile/index.php/tag/product/list/tagId/8/" style="font-size:95%;">gallery</a></li>
                <li><a href="http://m1.alothemes.com/smile/index.php/tag/product/list/tagId/14/" style="font-size:95%;">magento</a></li>
                <li><a href="http://m1.alothemes.com/smile/index.php/tag/product/list/tagId/6/" style="font-size:95%;">news</a></li>
                <li><a href="http://m1.alothemes.com/smile/index.php/tag/product/list/tagId/12/" style="font-size:95%;">photos</a></li>
                <li><a href="http://m1.alothemes.com/smile/index.php/tag/product/list/tagId/3/" style="font-size:95%;">products</a></li>
                <li><a href="http://m1.alothemes.com/smile/index.php/tag/product/list/tagId/7/" style="font-size:95%;">smile</a></li>
                <li><a href="http://m1.alothemes.com/smile/index.php/tag/product/list/tagId/5/" style="font-size:95%;">sports</a></li>
            </ul>
            <div class="actions">
                <a href="http://m1.alothemes.com/smile/index.php/tag/list/">View All Tags</a>
            </div>
        </div>
    </div>
</div>
