<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>


<div class="customer col-lg-3 col-md-3 col-sm-3 col-xs-12">
    <div class="block-static3 static-alo">
        <div class="block block-creare-twitter">
            <div class="block-title"><strong><span>Our Latest Tweets</span></strong></div>
            <span class="toggle-tab mobile" style="display: none;"><span class="hidden">hidden</span></span>
            <div class="block-content toggle-content">
                <?php $block->getTweets();?>
                <ul>
                    <li>
                        <p class="twitter-pic">
                            <a href="https://twitter.com/alothemes"><img src="http://pbs.twimg.com/profile_images/536002680057913345/j7c9SpAr_normal.png" alt="twitter icon"></a>
                        </p>
                        <p class="twitter-links">
                            <span class="tweetprofilelink">
    <strong><a href="https://twitter.com/alothemes">alothemes</a></strong>
    <a href="https://twitter.com/alothemes">@alothemes</a>
</span> Install only template wordpress ALO Themes: <a target="_Blank" href="https://t.co/XHjkgJIn63">https://t.co/XHjkgJIn63</a> via @YouTube <span> - 426 days ago</span>
                        </p>
                    </li>
                    <li>
                        <p class="twitter-pic">
                            <a href="https://twitter.com/alothemes"><img src="http://pbs.twimg.com/profile_images/536002680057913345/j7c9SpAr_normal.png" alt="twitter icon"></a>
                        </p>
                        <p class="twitter-links">
                            <span class="tweetprofilelink">
    <strong><a href="https://twitter.com/alothemes">alothemes</a></strong>
    <a href="https://twitter.com/alothemes">@alothemes</a>
</span> Install quickstart wordpress ALO Themes.: <a target="_Blank" href="https://t.co/mg5XEDrDZg">https://t.co/mg5XEDrDZg</a> via @YouTube <span> - 426 days ago</span>
                        </p>
                    </li>
                </ul>
            </div>
        </div>

    </div>
</div>

