<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block-static4 static-alo">
    <div class="block block-subscribe">
        <div class="block-title"><strong><span><?= $block->escapeHtml(__('Newsletter')) ?></span></strong></div>
        <span style="display: none;" class="toggle-tab mobile"><span class="hidden">hidden</span></span>
            <form class="form subscribe"
                novalidate
                action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
                method="post"
                data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                id="newsletter-validate-detail">
                <div class="block-content toggle-content">
                    <div class="form-subscribe-header">
                        <label class="newsletter" for="newsletter"><span><?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?></span></label>
                    </div>
                    <div class="control">
                        <input name="email" class="input-text required-entry validate-email" type="email" id="newsletter"
                                placeholder="<?= $block->escapeHtml(__('Enter your email address')) ?>"
                                data-mage-init='{"mage/trim-input":{}}'
                                data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </div>
                <div class="actions">
                    <button class="action button subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit">
                        <span><span><?= $block->escapeHtml(__('Subscribe')) ?></span></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
