<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<div class="paypal hidden-xs">
    <p><img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/paypal.png'); ?>" alt=""></p>
</div>
<a href="#" id="backtotop" style="display: block;"><span class="fa fa-angle-up"></span><span class="back-to-top">Back to Top</span></a>
