<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<!-- <div class="alo footer-container"> -->
    <div class="block-footer-copyright">
        <div class="container">
            <div class="footer">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 pull-left">
                        <ul class="links">
                            <li class="first"><a href="http://m1.alothemes.com/smile/index.php/catalog/seo_sitemap/category/">Site Map</a></li>
                            <li><a href="http://m1.alothemes.com/smile/index.php/catalogsearch/term/popular/">Search Terms</a></li>
                            <li><a href="http://m1.alothemes.com/smile/index.php/catalogsearch/advanced">Advanced Search</a></li>
                            <li><a href="http://m1.alothemes.com/smile/index.php/sales/guest/form">Orders and Returns</a></li>
                            <li class="last"><a href="http://m1.alothemes.com/smile/index.php/contacts">Contact Us</a></li>
                        </ul>
                        <address>
    <?= /* @escapeNotVerified */ $block->getCopyright() ?>
    </address>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 pull-right">
                        <div class="paypal hidden-xs">
                            <p><img class="img-responsive" src="http://m1.alothemes.com/smile/media/wysiwyg/alothemes/static/paypal.png" alt=""></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a href="#" id="backtotop" style="display: block;"><span class="fa fa-angle-up"></span><span class="back-to-top">Back to Top</span></a>
<!-- </div> -->