<div class="alo alo-slide">
    <div class="main">
        <div>
            <div class="magicslider">
                <div class="bx-wrapper" style="max-width: 100%;">
                    <div class="bx-viewport" style="width: 100%; overflow: hidden; position: relative; height: 505px;">
                        <div  class="smile_bxslider">
                            <?php if(!empty($block->getSlides())) { ?>
                            <?php foreach ($block->getSlides() as $key => $value) { ?>
                            <div class="item">
                                <a href="#">
                                    <img src="<?php echo $value['slide_image'];?>" alt="magicslider">
                                </a>
                                <div class="bx-caption">
                                    <div class="magic-caption">
                                        <div class="caption1"><?php echo $value['slide_title'];?></div>
                                        <div class="caption2 blackcaption">
                                            <p><?php echo $value['slide_description'];?></p>
                                        </div>
                                        <div class="caption3 blackcaption"><a href="#">SHOP NOW !</a></div>
                                    </div>
                                </div>
                            </div>
                            <?php } // foreach closed ?>
                            <?php } // if closed?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" xml="space">
    require([
        'jquery',
        'bxSlider'
    ], function($){
        $(document).ready(function() {
            $('.smile_bxslider').bxSlider( {
                auto: true,
			    captions: true,
                easing: "easeInSine",
                controls: 1, 
                pager: 1, 
                pause: 5000, 
                speed: 400,
                onSlideBefore: function(el) {
                        el.siblings().find('.bx-caption').removeClass('play');
                        el.find('.bx-caption').addClass('play').addClass('start');				
                        },
            });
        });
    });
</script>
